work

diff --git a/zephyr/.github/workflows/compliance.yml b/zephyr/.github/workflows/compliance.yml
--- a/zephyr/.github/workflows/compliance.yml
+++ b/zephyr/.github/workflows/compliance.yml
@@ -1,6 +1,15 @@
 name: Compliance Checks
 
-on: pull_request
+on:
+  pull_request:
+    types:
+    - edited
+    - opened
+    - reopened
+    - synchronize
+
+permissions:
+  contents: read
 
 jobs:
   check_compliance:
@@ -12,25 +21,12 @@ jobs:
         echo "$HOME/.local/bin" >> $GITHUB_PATH
 
     - name: Checkout the code
-      uses: actions/checkout@v3
+      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       with:
         ref: ${{ github.event.pull_request.head.sha }}
         fetch-depth: 0
 
-    - name: cache-pip
-      uses: actions/cache@v3
-      with:
-        path: ~/.cache/pip
-        key: ${{ runner.os }}-doc-pip
-
-    - name: Install python dependencies
-      run: |
-        pip3 install setuptools
-        pip3 install wheel
-        pip3 install python-magic lxml junitparser gitlint pylint pykwalify yamllint
-        pip3 install west
-
-    - name: west setup
+    - name: Rebase onto the target branch
       env:
         BASE_REF: ${{ github.base_ref }}
       run: |
@@ -40,12 +36,29 @@ jobs:
         # Ensure there's no merge commits in the PR
         [[ "$(git rev-list --merges --count origin/${BASE_REF}..)" == "0" ]] || \
         (echo "::error ::Merge commits not allowed, rebase instead";false)
+        rm -fr ".git/rebase-apply"
+        rm -fr ".git/rebase-merge"
         git rebase origin/${BASE_REF}
+        git clean -f -d
         # debug
         git log  --pretty=oneline | head -n 10
+
+    - name: Set up Python
+      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
+      with:
+        python-version: 3.12
+        cache: pip
+        cache-dependency-path: scripts/requirements-actions.txt
+
+    - name: Install Python packages
+      run: |
+        pip install -r scripts/requirements-actions.txt --require-hashes
+
+    - name: west setup
+      run: |
         west init -l . || true
-        west config manifest.group-filter -- +ci,+optional
-        west update 2>&1 1> west.update.log || west update 2>&1 1> west.update2.log
+        west config manifest.group-filter -- +ci,-optional
+        west update -o=--depth=1 -n 2>&1 1> west.update.log || west update -o=--depth=1 -n 2>&1 1> west.update2.log
 
     - name: Run Compliance Tests
       continue-on-error: true
@@ -57,11 +70,17 @@ jobs:
         # debug
         ls -la
         git log  --pretty=oneline | head -n 10
-        ./scripts/ci/check_compliance.py --annotate -e KconfigBasic \
-        -c origin/${BASE_REF}..
+        # Increase rename limit to allow for large PRs
+        git config diff.renameLimit 10000
+        excludes="-e KconfigBasic -e SysbuildKconfigBasic -e ClangFormat"
+        # The signed-off-by check for dependabot should be skipped
+        if [ "${{ github.actor }}" == "dependabot[bot]" ]; then
+          excludes="$excludes -e Identity"
+        fi
+        ./scripts/ci/check_compliance.py --annotate $excludes -c origin/${BASE_REF}..
 
     - name: upload-results
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
       continue-on-error: true
       with:
         name: compliance.xml
@@ -73,19 +92,33 @@ jobs:
           exit 1;
         fi
 
+        warns=("ClangFormat")
         files=($(./scripts/ci/check_compliance.py -l))
+
         for file in "${files[@]}"; do
           f="${file}.txt"
           if [[ -s $f ]]; then
-            errors=$(cat $f)
-            errors="${errors//'%'/'%25'}"
-            errors="${errors//$'\n'/'%0A'}"
-            errors="${errors//$'\r'/'%0D'}"
-            echo "::error file=${f}::$errors"
-            exit=1
+            results=$(cat $f)
+            results="${results//'%'/'%25'}"
+            results="${results//$'\n'/'%0A'}"
+            results="${results//$'\r'/'%0D'}"
+
+            if [[ "${warns[@]}" =~ "${file}" ]]; then
+              echo "::warning file=${f}::$results"
+            else
+              echo "::error file=${f}::$results"
+              exit=1
+            fi
           fi
         done
 
         if [ "${exit}" == "1" ]; then
+          echo "Compliance error, check for error messages in the \"Run Compliance Tests\" step"
+          echo "You can run this step locally with the ./scripts/ci/check_compliance.py script."
+          exit 1;
+        fi
+
+        if [ "${{ steps.pr_description.outcome }}" == "failure" ]; then
+          echo "PR description cannot be empty"
           exit 1;
         fi
